/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.HeadlessException;
import java.beans.PropertyVetoException;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.collections.map.HashedMap;

/**
 *
 * @author PC
 */
public class ReporteVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteVentas
     */
    public static String x;

    public ReporteVentas() {
        initComponents();
        x = "x";

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void imprimirReporte() throws HeadlessException {
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ConexionTienda cc = new ConexionTienda();
            Connection cn = cc.conectar();
            Map parametros = new HashedMap();
            if (jComboBox_Ventas.getSelectedItem().equals("GENERAL")) {
                //parametros.put("placa", txtReportes.getText());
                // JasperReport reporte = (JasperReport) JRLoader.loadObject("src\\Reportes\\rptProductos.jrxml");
                JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/rptVentasGenerales.jasper"));
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, null, cn);
                // JasperViewer.viewReport(imprimir);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                try {

                    frame.setMaximum(true);
                } catch (Exception e) {
                }
                frame.setVisible(true);
            }
            if (jComboBox_Ventas.getSelectedItem().equals("N VENTA")) {
                parametros.put("numVenta", jTextField_Reportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\Reportes\\reporteAutoxPlaca.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                try {

                    frame.setMaximum(true);
                } catch (Exception e) {
                }
                frame.setVisible(true);

            }
            if (jComboBox_Ventas.getSelectedItem().equals("CÉDULA")) {
                if (Metodos.verificadorCédula(jTextField_Reportes.getText())) {
                    FacturaCliente fac = new FacturaCliente(null, true, jTextField_Reportes.getText());
                    if (fac.clienteExiste) {
                        fac.setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Cédula incorrecta");
                }


            }
            if (jComboBox_Ventas.getSelectedItem().equals("MARCA")) {
                parametros.put("marca", jTextField_Reportes.getText());
                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteAutoxMarca.jrxml");
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                frame.setVisible(true);
            }
//            if (jComboBox_Ventas.getSelectedItem().equals("FECHA")) {
//                parametros.put("fecha", jTextField_Reportes.getText());
//                JasperReport reporte = JasperCompileManager.compileReport("src\\reportes\\reporteAutoxAño.jrxml");
//                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
//                JInternalFrame frame = new JInternalFrame("Reporte");
//                frame.getContentPane().add(new JRViewer(imprimir));
//                frame.pack();
//                frame.setResizable(true);
//                frame.setClosable(true);
//                frame.setMaximizable(true);
//                frame.setSize(1000, 700);
//                Menu.jDesktopPane1.add(frame);
//                frame.setVisible(true);
//            }
            if (jComboBox_Ventas.getSelectedItem().equals("SELECCIONE")) {
                JOptionPane.showMessageDialog(null, "SELECCIONE OPCION");
            }

            //JasperViewer.viewReport(imprimir,false);
        } catch (JRException ex) {
        }
    }

    public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ReporteVentas().setVisible(true);
            }
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox_Ventas = new javax.swing.JComboBox();
        jTextField_Reportes = new javax.swing.JTextField();
        btn_Generar_Reporte = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Buscar por: ");

        jComboBox_Ventas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "GENERAL", "CÉDULA" }));
        jComboBox_Ventas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_VentasItemStateChanged(evt);
            }
        });

        btn_Generar_Reporte.setText("Generar Reporte");
        btn_Generar_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Generar_ReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_Ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jTextField_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Generar_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_Ventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Generar_Reporte))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Generar_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Generar_ReporteActionPerformed
        // TODO add your handling code here:
        imprimirReporte();
    }//GEN-LAST:event_btn_Generar_ReporteActionPerformed

    private void jComboBox_VentasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_VentasItemStateChanged
        // TODO add your handling code here:
        if (jComboBox_Ventas.getSelectedItem().equals("GENERAL")) {
            jTextField_Reportes.setEnabled(false);
        } else {
            jTextField_Reportes.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox_VentasItemStateChanged

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        x = null;
    }//GEN-LAST:event_formInternalFrameClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Generar_Reporte;
    private javax.swing.JComboBox jComboBox_Ventas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField_Reportes;
    // End of variables declaration//GEN-END:variables
}
