/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.util.Map;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;
import org.apache.commons.collections.map.HashedMap;

/**
 *
 * @author PC
 */
public class ReporteProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReporteProductos
     */
    public static String x;
    
    public ReporteProductos() {
        initComponents();
        setTitle("Reporte Productos");
        x = "x";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox_Productos = new javax.swing.JComboBox();
        jTextField_Reportes = new javax.swing.JTextField();
        btn_Generar_Reporte = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Buscar por: ");

        jComboBox_Productos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE", "GENERAL", "CÓDIGO", "NOMBRE", "MARCA" }));
        jComboBox_Productos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ProductosItemStateChanged(evt);
            }
        });

        btn_Generar_Reporte.setText("Generar Reporte");
        btn_Generar_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Generar_ReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Generar_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Generar_Reporte))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_ProductosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ProductosItemStateChanged
        // TODO add your handling code here:
        if (jComboBox_Productos.getSelectedItem().equals("GENERAL")) {
            jTextField_Reportes.setEnabled(false);
        } else {
            jTextField_Reportes.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox_ProductosItemStateChanged
    
    private void btn_Generar_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Generar_ReporteActionPerformed
        // TODO add your handling code here:
        imprimirReporte();
    }//GEN-LAST:event_btn_Generar_ReporteActionPerformed
    
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        x = null;
    }//GEN-LAST:event_formInternalFrameClosing
    public void imprimirReporte() throws HeadlessException {
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ConexionTienda cc = new ConexionTienda();
            Connection cn = cc.conectar();
            Map parametros = new HashedMap();
            if (jComboBox_Productos.getSelectedItem().equals("GENERAL")) {
                //parametros.put("placa", txtReportes.getText());
                // JasperReport reporte = (JasperReport) JRLoader.loadObject("src\\Reportes\\rptProductos.jrxml");
                JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/rptProductos.jasper"));
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, null, cn);
                // JasperViewer.viewReport(imprimir);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                try {
                    
                    frame.setMaximum(true);
                } catch (Exception e) {
                }
                frame.setVisible(true);
            } else if (jComboBox_Productos.getSelectedItem().equals("CÓDIGO")) {
                parametros.put("codigo", jTextField_Reportes.getText());
                JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/rptProductosCodigo.jasper"));
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                try {
                    
                    frame.setMaximum(true);
                } catch (Exception e) {
                }
                frame.setVisible(true);
                
            }
            if (jComboBox_Productos.getSelectedItem().equals("NOMBRE")) {
                parametros.put("nombre", jTextField_Reportes.getText());
                JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/rptProductoNombre.jasper"));
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                try {
                    
                    frame.setMaximum(true);
                } catch (Exception e) {
                }
                frame.setVisible(true);
            }
            if (jComboBox_Productos.getSelectedItem().equals("MARCA")) {
                parametros.put("marca", jTextField_Reportes.getText());
                JasperReport reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/rptProductosMarca.jasper"));
                JasperPrint imprimir = JasperFillManager.fillReport(reporte, parametros, cn);
                JInternalFrame frame = new JInternalFrame("Reporte");
                frame.getContentPane().add(new JRViewer(imprimir));
                frame.pack();
                frame.setResizable(true);
                frame.setClosable(true);
                frame.setMaximizable(true);
                frame.setSize(1000, 700);
                Menu.jDesktopPane1.add(frame);
                try {
                    
                    frame.setMaximum(true);
                } catch (Exception e) {
                }
                frame.setVisible(true);
            }
            
            if (jComboBox_Productos.getSelectedItem().equals("SELECCIONE")) {
                JOptionPane.showMessageDialog(null, "SELECCIONE OPCION");
            }

            //JasperViewer.viewReport(imprimir,false);
        } catch (JRException ex) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new ReporteProductos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Generar_Reporte;
    private javax.swing.JComboBox jComboBox_Productos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField_Reportes;
    // End of variables declaration//GEN-END:variables
}
